//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Admin1 = new HashSet<Admin>();
            this.Contents = new HashSet<Content>();
            this.Pages = new HashSet<Page>();
            this.SystemLogs = new HashSet<SystemLog>();
            this.TypeContents = new HashSet<TypeContent>();
            this.TypePages = new HashSet<TypePage>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> DateLogin { get; set; }
        public Nullable<bool> Order { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> Parent { get; set; }
    
        public virtual ICollection<Admin> Admin1 { get; set; }
        public virtual Admin Admin2 { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<SystemLog> SystemLogs { get; set; }
        public virtual ICollection<TypeContent> TypeContents { get; set; }
        public virtual ICollection<TypePage> TypePages { get; set; }
    }
}
