//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.ImageProducts = new HashSet<ImageProduct>();
            this.Status1 = new HashSet<Status>();
            this.Tags = new HashSet<Tag>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ImageContents = new HashSet<ImageContent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Image { get; set; }
        public string Summary { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateByAdminId { get; set; }
        public int TypeId { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public int GroupId { get; set; }
        public Nullable<bool> IsHomePage { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual GroupContent GroupContent { get; set; }
        public virtual TypeContent TypeContent { get; set; }
        public virtual ICollection<ImageProduct> ImageProducts { get; set; }
        public virtual ICollection<Status> Status1 { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ImageContent> ImageContents { get; set; }
    }
}
