//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HopNguyenEntities : DbContext
    {
        public HopNguyenEntities()
            : base("name=HopNguyenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<GroupContent> GroupContents { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<ImageProduct> ImageProducts { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<PageDetail> PageDetails { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Support> Supports { get; set; }
        public DbSet<SystemLog> SystemLogs { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TypeContent> TypeContents { get; set; }
        public DbSet<TypeImage> TypeImages { get; set; }
        public DbSet<TypePage> TypePages { get; set; }
        public DbSet<TypeSupport> TypeSupports { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<ImageContent> ImageContents { get; set; }
    }
}
