//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupContent
    {
        public GroupContent()
        {
            this.Contents = new HashSet<Content>();
            this.Status = new HashSet<Status>();
            this.TypeContents = new HashSet<TypeContent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
        public virtual ICollection<Status> Status { get; set; }
        public virtual ICollection<TypeContent> TypeContents { get; set; }
    }
}
