//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Sort { get; set; }
        public int GroupId { get; set; }
    
        public virtual GroupContent GroupContent { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
    }
}
