//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Nick { get; set; }
        public string Email { get; set; }
        public string Summary { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual TypeSupport TypeSupport { get; set; }
    }
}
