//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeContent
    {
        public TypeContent()
        {
            this.Contents = new HashSet<Content>();
            this.TypeContent1 = new HashSet<TypeContent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Image { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> CreateByAdminId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public int GroupId { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
        public virtual GroupContent GroupContent { get; set; }
        public virtual ICollection<TypeContent> TypeContent1 { get; set; }
        public virtual TypeContent TypeContent2 { get; set; }
    }
}
