//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeImage
    {
        public TypeImage()
        {
            this.Images = new HashSet<Image>();
            this.TypeImage1 = new HashSet<TypeImage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Parent { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<TypeImage> TypeImage1 { get; set; }
        public virtual TypeImage TypeImage2 { get; set; }
    }
}
