//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopNguyenModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeSupport
    {
        public TypeSupport()
        {
            this.Supports = new HashSet<Support>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Pattern { get; set; }
        public string Parameter { get; set; }
    
        public virtual ICollection<Support> Supports { get; set; }
    }
}
